'use strict';
const $=s=>document.querySelector(s);
const all=s=>Array.from(document.querySelectorAll(s));
const BLOCKS={
 trigger:{name:'Monitor trigger',short:'Trigger',icon:'↳',sub:'PRTG · read sensor',description:'Start an investigation for one mapped sensor. This preview runs on demand; background scheduling is not enabled.'},
 ssot:{name:'Source of truth',short:'SSOT',icon:'◈',sub:'Device · service · owner',description:'Resolve identity and business context from your verified asset register. Live runs reject sample or stale records.'},
 knowledge:{name:'Approved runbooks',short:'Knowledge',icon:'▤',sub:'Mapped procedures',description:'Use the runbook IDs attached to this asset. This release retrieves whole mapped runbooks, without embeddings or a vector database.'},
 model:{name:'Local language model',short:'Local AI',icon:'✧',sub:'Your installed model',description:'Use an installed model through a local OpenAI-compatible API. It can help draft the agent instructions and summarize evidence.'},
 history:{name:'Sensor history',short:'History',icon:'≋',sub:'Timestamped values',description:'Read numeric PRTG history in the exact unit and channel declared in the SSOT.'},
 quality:{name:'Data quality',short:'Validate',icon:'✓',sub:'Fresh · regular · complete',description:'Reject missing buckets, duplicate timestamps, incomplete sampling, nonnumeric values and stale telemetry. No silent filling of gaps.'},
 forecast:{name:'TimesFM 2.5',short:'Forecast',icon:'⌁',sub:'Local metric forecasting',description:'Estimate future metric values and compare three chronological holdouts with a seasonal-naive baseline. Sample mode uses a labelled trend baseline.'},
 policy:{name:'Human approval',short:'Permissions',icon:'◇',sub:'Review before delivery',description:'Read-only tools. Review the exact generated text before sending to one locally configured Slack channel. No network changes are permitted.'},
 output:{name:'Slack draft',short:'Output',icon:'#',sub:'One approved channel',description:'Prepare an incident or forecast update. Credentials stay in your local environment. External delivery is disabled in sample mode.'}
};
const BASE={schema_version:'0.1',approval_required:true,sensor_id:'1001',threshold:80,direction:'above',horizon:24,interval:300,period:288,model:'',positions:{}};
const presets={triage:{...BASE,template:'triage',name:'Incident brief',purpose:'Investigate a monitoring alert using verified device ownership, service context and approved runbooks. Separate observations from hypotheses. Prepare a concise update for human review.',nodes:['trigger','ssot','knowledge','model','policy','output']},forecast:{...BASE,template:'forecast',name:'Capacity forecast',purpose:'Forecast metric threshold crossings from complete monitoring history. Report uncertainty and baseline performance. Use SSOT ownership to route a reviewable risk brief; never claim a forecast proves an outage.',nodes:['trigger','ssot','history','quality','forecast','model','knowledge','policy','output']}};
let agents=structuredClone(presets),current='triage',selected='ssot',runtime=null,ssot=null,lastResult=null,busy=false;
try{let saved=JSON.parse(localStorage.getItem('bya-agents-v1'));if(saved){for(const k of ['triage','forecast'])if(saved[k]){validateAgent(saved[k]);agents[k]=saved[k]}}}catch{}
function agent(){return agents[current]}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function validateAgent(a){if(!a||!['triage','forecast'].includes(a.template)||!Array.isArray(a.nodes)||a.nodes.some(n=>!BLOCKS[n])||a.approval_required!==true)throw Error('Invalid agent package. Use a BYA v0.1 template with approval enabled.');if(new Set(a.nodes).size!==a.nodes.length)throw Error('Duplicate blocks are not allowed.');if(!Number.isInteger(a.horizon)||a.horizon<1||a.horizon>96||!Number.isFinite(a.threshold)||!/^\d+$/.test(a.sensor_id))throw Error('Check sensor ID, threshold and forecast horizon.');if(!['above','below'].includes(a.direction)||a.interval<60||a.interval>86400||!Number.isInteger(a.period)||a.period<1)throw Error('Invalid forecasting settings.');}
function exportFile(name,value){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function showView(view){$('#builder-view').hidden=view!=='builder';$('#ssot-view').hidden=view!=='ssot';all('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='ssot')renderSSOT();else renderCanvas()}
function chooseTemplate(t){if(!presets[t])throw Error('Unknown template.');current=t;selected='ssot';lastResult=null;$('#run-output').hidden=true;$('#run-empty').hidden=false;$('#crumb').textContent=agent().name;$('#agent-title').textContent=t==='triage'?'From alert to understanding.':'Get ahead of capacity risk.';$('#agent-subtitle').textContent=t==='triage'?'An evidence-backed incident brief, ready for your review.':'Forecast metric thresholds with infrastructure context.';all('[data-template]').forEach(b=>b.classList.toggle('selected',b.dataset.template===t));showView('builder');renderPalette();renderInspector();renderCanvas()}
function renderPalette(){const order=current==='triage'?['trigger','ssot','knowledge','model','policy','output']:['trigger','ssot','history','quality','forecast','knowledge','model','policy','output'];$('#palette').innerHTML=order.map((k,i)=>`<button draggable="true" data-add="${k}" class="${agent().nodes.includes(k)?'active':''}"><span>${String(i+1).padStart(2,'0')}</span>${BLOCKS[k].short}</button>`).join('');all('[data-add]').forEach(b=>{b.onclick=()=>addNode(b.dataset.add);b.ondragstart=e=>{e.dataTransfer.setData('text/plain',b.dataset.add);e.dataTransfer.effectAllowed='copy'}})}
function addNode(k){if(!BLOCKS[k])return;if(!presets[current].nodes.includes(k))return;if(!agent().nodes.includes(k))agent().nodes.push(k);selected=k;renderPalette();renderCanvas();renderInspector()}
function defaults(){let w=$('#canvas').clientWidth;const nw=w>580?156:(w<=400?145:135);const cols=w>=600?3:2;const rows=Math.ceil(agent().nodes.length/cols);const gap=Math.max(12,(w-cols*nw)/(cols+1));const result={};agent().nodes.forEach((k,i)=>{let row=Math.floor(i/cols),col=i%cols;if(row%2)col=cols-1-col;result[k]={x:Math.max(8,gap+col*(nw+gap)),y:30+row*135}});$('#canvas').style.minHeight=Math.max(440,rows*135+50)+'px';return result}
function edges(){return current==='triage'?[['trigger','ssot'],['ssot','knowledge'],['knowledge','policy'],['model','policy','support'],['policy','output']]:[['trigger','ssot'],['ssot','history'],['history','quality'],['quality','forecast'],['forecast','policy'],['knowledge','policy','support'],['model','policy','support'],['policy','output']]}
function renderCanvas(){if($('#builder-view').hidden)return;const pos=defaults();const width=$('#canvas').clientWidth;$('#nodes').innerHTML=agent().nodes.map(k=>{let saved=agent().positions?.[k];let p=saved?{x:Math.max(6,Math.min(saved.x,width-162)),y:Math.max(6,Math.min(saved.y,$('#canvas').clientHeight-94))}:pos[k];return `<button class="node ${selected===k?'selected':''} ${k==='ssot'?'ssot-node':''} ${['model','knowledge'].includes(k)?'support':''}" data-node="${k}" style="left:${p.x}px;top:${p.y}px" aria-label="Configure ${BLOCKS[k].name}"><span class="node-top"><span class="node-icon">${BLOCKS[k].icon}</span>${k==='ssot'?'AUTHORITY':k==='forecast'?'PREDICTION':k==='policy'?'CONTROL':'COMPONENT'}</span><strong>${BLOCKS[k].name}</strong><small>${BLOCKS[k].sub}</small><i class="node-dot"></i><i class="node-dot node-input"></i></button>`}).join('');$('#block-count').textContent=agent().nodes.length;all('[data-node]').forEach(n=>{n.onclick=()=>{selected=n.dataset.node;renderInspector();all('[data-node]').forEach(b=>b.classList.toggle('selected',b===n))};let drag=null;n.onpointerdown=e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,left:n.offsetLeft,top:n.offsetTop};n.setPointerCapture(e.pointerId)};n.onpointermove=e=>{if(!drag)return;const x=Math.max(5,Math.min(drag.left+e.clientX-drag.x,width-n.offsetWidth-5));const y=Math.max(5,Math.min(drag.top+e.clientY-drag.y,$('#canvas').clientHeight-n.offsetHeight-5));n.style.left=x+'px';n.style.top=y+'px';agent().positions??={};agent().positions[n.dataset.node]={x,y};drawWires()};n.onpointerup=()=>{drag=null};n.onpointercancel=()=>{drag=null}});drawWires()}
function drawWires(){const c=$('#canvas'),svg=$('#wires');svg.setAttribute('viewBox',`0 0 ${c.clientWidth} ${c.clientHeight}`);svg.innerHTML=edges().filter(([a,b])=>agent().nodes.includes(a)&&agent().nodes.includes(b)).map(([a,b,type])=>{const x=$(`[data-node="${a}"]`),y=$(`[data-node="${b}"]`);if(!x||!y)return '';const right=y.offsetLeft>=x.offsetLeft;let x1=x.offsetLeft+(right?x.offsetWidth:0),y1=x.offsetTop+40,x2=y.offsetLeft+(right?0:y.offsetWidth),y2=y.offsetTop+40;const d=right?38:-38;return `<path d="M${x1} ${y1} C${x1+d} ${y1},${x2-d} ${y2},${x2} ${y2}" fill="none" stroke="${type?'#9aafa7':'#9baebb'}" stroke-width="1.4" ${type?'stroke-dasharray="4 4"':''}/>`}).join('')}
function field(label,key,type='text',extra=''){return `<label class="field">${label}<input data-setting="${key}" type="${type}" value="${esc(agent()[key])}" ${extra}></label>`}
function renderInspector(){const b=BLOCKS[selected];$('#node-title').textContent=b.name;$('#node-description').textContent=b.description;let content='';if(selected==='trigger')content=field('PRTG sensor ID','sensor_id')+`<span class="field-help">Only IDs mapped in your source of truth can run.</span>`;
 if(selected==='ssot'){let a=ssot?.assets.find(a=>a.sensors.some(s=>String(s.id)===agent().sensor_id));content=`<span class="status-pill">${a?'Mapped asset':'Mapping required'}</span><label class="field">Asset<input readonly value="${esc(a?.name||'Not mapped')}"></label><label class="field">Service owner<input readonly value="${esc(a?.owner||'Not mapped')}"></label><button class="button" id="inspect-ssot">Open source of truth ↗</button>`}
 if(selected==='model')content=`<label class="field">Agent instructions<textarea data-setting="purpose" rows="6">${esc(agent().purpose)}</textarea></label><button class="button" id="assist">✧ Refine with local AI</button><span class="field-help">${runtime?'Uses '+esc(runtime.model||'your configured model')+'.':'Install the runtime to use your own model.'}</span>`;
 if(selected==='knowledge')content=`<span class="status-pill">Explicit runbook mapping</span><p class="field-help">Each SSOT record lists approved runbook IDs. Edit runbooks.json in the local package to add your own procedures.</p><button class="button" id="inspect-ssot">Inspect asset mappings ↗</button>`;
 if(selected==='history')content=field('Sample interval (seconds)','interval','number','min="60" max="86400"')+`<span class="field-help">Use the same interval in PRTG history and the forecasting model. History defaults to 72 hours in local configuration.</span>`;
 if(selected==='quality')content=`<span class="status-pill">Blocking checks enabled</span><p class="field-help">✓ Unique timestamps<br>✓ Regular sample interval<br>✓ Numeric readings<br>✓ Full sampling coverage<br>✓ Fresh SSOT and telemetry<br>✓ Enough history for backtesting</p>`;
 if(selected==='forecast')content=field('Threshold (channel units)','threshold','number','step="any"')+`<label class="field">Crossing direction<select data-setting="direction"><option value="above" ${agent().direction==='above'?'selected':''}>Above threshold</option><option value="below" ${agent().direction==='below'?'selected':''}>Below threshold</option></select></label>`+field('Forecast horizon (samples)','horizon','number','min="1" max="96"')+field('Seasonal baseline (samples)','period','number','min="1"')+`<span class="field-help">24 samples × 5 minutes = 2 hours. A 288-sample baseline repeats the previous day at 5-minute intervals.</span>`;
 if(selected==='policy')content=`<span class="status-pill">Approval always required</span><p class="field-help">The local runtime enforces approval independently of model instructions. Failed baseline comparisons block forecast delivery. Sample data never sends real messages.</p>`;
 if(selected==='output')content=`<label class="field">Delivery target<input readonly value="Configured local Slack channel"></label><button class="button" id="connect-settings">Connection setup ↗</button><span class="field-help">The destination is fixed locally. The model cannot choose recipients or access tokens.</span>`;
 content+=`<button class="text-button" id="remove-block" style="margin-top:20px">Remove block</button>`;$('#node-settings').innerHTML=content;
 all('[data-setting]').forEach(input=>input.onchange=()=>{let key=input.dataset.setting;agent()[key]=input.type==='number'?Number(input.value):input.value;lastResult=null;$('#run-output').hidden=true;$('#run-empty').hidden=false});$('#inspect-ssot')?.addEventListener('click',()=>showView('ssot'));$('#connect-settings')?.addEventListener('click',()=>$('#connections-dialog').showModal());$('#assist')?.addEventListener('click',assist);$('#remove-block').onclick=()=>{agent().nodes=agent().nodes.filter(k=>k!==selected);renderPalette();renderCanvas();toast('Block removed. Drag it back from the shelf before running.');lastResult=null;$('#run-output').hidden=true;$('#run-empty').hidden=false}}
function validateSSOT(doc){if(!Array.isArray(doc.assets)||!doc.assets.length)throw Error('SSOT needs an assets array.');const ids=new Set(),sensors=new Set();for(const a of doc.assets){for(const k of ['id','name','owner','service','source','verified_at','sensors'])if(!a[k])throw Error('Missing SSOT field: '+k);if(ids.has(a.id)||!Number.isFinite(Date.parse(a.verified_at)))throw Error('Duplicate identity or invalid verification date.');ids.add(a.id);if(!Array.isArray(a.sensors)||!a.sensors.length)throw Error('Asset needs sensor mappings.');for(const s of a.sensors){if(!/^\d+$/.test(String(s.id))||sensors.has(String(s.id))||!s.channel||!s.unit)throw Error('Sensor IDs must be unique with channel and unit.');sensors.add(String(s.id))}}return doc}
function renderSSOT(){if(!ssot)return;$('#ssot-rows').innerHTML=ssot.assets.map(a=>`<tr><td><strong>${esc(a.name)}</strong><small>${esc(a.id)} · ${esc(a.site||'')}</small></td><td>${esc(a.service)}<small>${esc(a.owner)}</small></td><td>${a.sensors.map(s=>`${esc(s.id)} · ${esc(s.channel)}<small>${esc(s.unit)}</small>`).join('')}</td><td>${esc(a.source)}<small>${esc(a.verified_at.slice(0,10))}${a.sample?' · SAMPLE':''}</small></td></tr>`).join('')}
async function api(path,body){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-BYA-Token':runtime?.token||''},body:JSON.stringify(body)});let data=await res.json();if(!res.ok)throw Error(data.error||'Local operation failed.');return data}
function busyState(value){busy=value;$('#run-top').disabled=value;$('#run-bottom').disabled=value;$('#run-bottom').textContent=value?'Running…':'▷ Run test'}
async function assist(){if(!runtime){$('#download-dialog').showModal();return}const button=$('#assist');button.disabled=true;button.textContent='Refining…';try{const r=await api('/api/assist',{goal:agent().purpose});agent().purpose=r.instructions;renderInspector();toast('Instructions updated by your local model. Review them before running.')}catch(e){toast(e.message);button.disabled=false;button.textContent='✧ Refine with local AI'}}
function linear(values,horizon){const tail=values.slice(-24),n=tail.length,x=(n-1)/2,y=tail.reduce((a,b)=>a+b,0)/n;const slope=tail.reduce((s,v,i)=>s+(i-x)*(v-y),0)/tail.reduce((s,_,i)=>s+(i-x)**2,0);return Array.from({length:horizon},(_,i)=>y+slope*(n+i-x))}
function sampleRun(){const a=agent();const match=ssot.assets.filter(x=>x.sensors.some(s=>String(s.id)===a.sensor_id));if(match.length!==1)throw Error('No unique SSOT mapping for this sensor.');const asset=match[0],sensor=asset.sensors.find(s=>String(s.id)===a.sensor_id);const trace=[{step:'Sample input',detail:'Synthetic monitoring data; no external calls'},{step:'SSOT',detail:`${asset.name} · ${asset.service} · ${asset.owner}`},{step:'Knowledge',detail:(asset.runbook_ids||[]).join(', ')||'No approved runbooks mapped'}];const result={id:'sample-'+Date.now(),mode:'sample',status:'awaiting_approval',trace};if(current==='triage'){result.draft=`[SAMPLE] ${asset.name} reports elevated interface utilization. Potential service impact: ${asset.service}. Owner: ${asset.owner}. Review sustained traffic and interface errors using ${(asset.runbook_ids||[]).join(', ')||'an approved procedure'}. Root cause remains unconfirmed. No changes have been executed.`;trace.push({step:'Sample analysis',detail:'Deterministic sample text · no LLM inference'})}else{const values=Array.from({length:576},(_,i)=>40+.055*i+4*Math.sin(i*2*Math.PI/288)),h=a.horizon,fold=Math.min(h,12);if(values.length<Math.max(a.period,48)+3*fold)throw Error('The sample has 576 points. Reduce baseline period or supply more history locally.');const es=[],bs=[];for(const k of [3,2,1]){let end=values.length-k*fold,train=values.slice(0,end),actual=values.slice(end,end+fold),p=linear(train,fold);actual.forEach((v,i)=>{es.push(Math.abs(v-p[i]));bs.push(Math.abs(v-train[train.length-a.period+i%a.period]))})}let p=linear(values,h),mae=es.reduce((a,b)=>a+b,0)/es.length,bmae=bs.reduce((a,b)=>a+b,0)/bs.length;let idx=p.findIndex(v=>a.direction==='above'?v>=a.threshold:v<=a.threshold);result.forecast={history:values.slice(-96),point:p,threshold:a.threshold,unit:sensor.unit,backend:'demo-trend',mae,baseline_mae:bmae,beats_baseline:mae<bmae,interval_seconds:a.interval,crossing_step:idx<0?null:idx+1,lower:null,upper:null};result.draft=`[SAMPLE / trend baseline] ${asset.name} · ${sensor.channel}: ${idx<0?'No point-forecast threshold crossing within this horizon.':`Point forecast crosses ${a.threshold} ${sensor.unit} in ${(idx+1)*a.interval/60} minutes.`} Service: ${asset.service}; owner: ${asset.owner}. Holdout MAE ${mae.toFixed(2)}, seasonal baseline MAE ${bmae.toFixed(2)}. This is a metric forecast, not proof of an outage. TimesFM has not run in this sample.`;if(mae>=bmae)result.status='evaluation_only';trace.push({step:'Quality',detail:'576 synthetic, regularly spaced readings'},{step:'Forecast',detail:'Trend baseline · TimesFM available in local mode'},{step:'Backtest',detail:'3 chronological holdouts · seasonal comparison'})}trace.push({step:'Approval',detail:'No external messages sent'});return result}
async function runTest(){if(busy)return;try{validateAgent(agent());let missing=presets[current].nodes.filter(k=>!agent().nodes.includes(k));if(missing.length)throw Error('Restore these blocks: '+missing.map(k=>BLOCKS[k].short).join(', '));if(!ssot)throw Error('SSOT is still loading.');busyState(true);$('#test-heading').textContent='Following the evidence…';const snapshot=structuredClone(agent());const mode=$('#run-mode').value;if(mode==='live'&&!runtime)throw Error('Live runs require the local runtime.');lastResult=runtime?await api('/api/run',{...snapshot,mode}):sampleRun();renderResult();$('#test-heading').textContent='Evidence, ready for review.';$('#run-output').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){toast(e.message);$('#test-heading').textContent='Run blocked — review the message.'}finally{busyState(false)}}
function renderResult(){const r=lastResult;$('#run-empty').hidden=true;$('#run-output').hidden=false;$('#trace').innerHTML=r.trace.map(t=>`<div class="trace-item"><strong>${esc(t.step)}</strong><p>${esc(t.detail)}</p></div>`).join('');$('#draft-text').textContent=r.draft;$('#draft-state').textContent=r.status==='evaluation_only'?'Evaluation only':'Awaiting review';$('#approve').disabled=r.mode!=='live'||r.status!=='awaiting_approval';$('#delivery-note').textContent=r.mode==='sample'?'Sample drafts cannot send messages.':r.status==='evaluation_only'?'Forecast did not beat baseline; delivery blocked.':'Sends this exact draft to the channel configured locally.';$('#forecast-panel').hidden=!r.forecast;if(r.forecast)drawForecast()}
function drawForecast(){if(!lastResult?.forecast||$('#forecast-panel').hidden)return;const f=lastResult.forecast,svg=$('#forecast-chart'),w=Math.max(280,svg.clientWidth),h=230,left=42,right=20,top=16,bottom=35;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const values=[...f.history,...f.point,...(f.lower||[]),...(f.upper||[]),f.threshold],min=Math.min(...values),max=Math.max(...values),pad=Math.max((max-min)*.1,1),lo=min-pad,hi=max+pad,n=f.history.length+f.point.length;const x=i=>left+i/(n-1)*(w-left-right),y=v=>top+(hi-v)/(hi-lo)*(h-top-bottom),path=(arr,start)=>arr.map((v,i)=>(i?'L':'M')+x(start+i).toFixed(2)+' '+y(v).toFixed(2)).join(' ');let markup='';for(let i=0;i<4;i++){let v=lo+(hi-lo)*i/3;markup+=`<line x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}" stroke="#e5ebef"/><text x="${left-8}" y="${y(v)+4}" text-anchor="end" font-size="11" fill="#758497">${v.toFixed(0)}</text>`}if(f.lower&&f.upper){let area=path(f.lower,f.history.length)+' '+f.upper.map((_,i)=>{let j=f.upper.length-1-i;return 'L'+x(f.history.length+j)+' '+y(f.upper[j])}).join(' ')+' Z';markup+=`<path d="${area}" fill="#d7ece3"/>`}markup+=`<line x1="${left}" y1="${y(f.threshold)}" x2="${w-right}" y2="${y(f.threshold)}" stroke="#c89152" stroke-dasharray="5 4"/><text x="${left+4}" y="${y(f.threshold)-5}" font-size="11" fill="#a0743f">Threshold ${f.threshold} ${esc(f.unit)}</text><path d="${path(f.history,0)}" fill="none" stroke="#687f97" stroke-width="2"/><path d="${path([f.history.at(-1),...f.point],f.history.length-1)}" fill="none" stroke="#278369" stroke-width="2" stroke-dasharray="5 3"/><line x1="${x(f.history.length-1)}" y1="${top}" x2="${x(f.history.length-1)}" y2="${h-bottom}" stroke="#a9b6bf" stroke-dasharray="2 4"/><text x="${left}" y="${h-10}" font-size="11" fill="#758497">History (${esc(f.unit)})</text><text x="${x(f.history.length-1)-5}" y="${h-10}" text-anchor="end" font-size="11" fill="#758497">Now</text><text x="${w-right}" y="${h-10}" text-anchor="end" font-size="11" fill="#278369">+${f.point.length*f.interval_seconds/60} min</text>`;svg.innerHTML=markup;$('#forecast-backend').textContent=f.backend==='demo-trend'?'Sample trend · no uncertainty interval':'TimesFM 2.5 · q10–q90 range';$('#forecast-metrics').innerHTML=`<span>Holdout MAE<strong>${f.mae.toFixed(2)}</strong></span><span>Seasonal baseline MAE<strong>${f.baseline_mae.toFixed(2)}</strong></span><span>Baseline comparison<strong>${f.beats_baseline?'Lower error':'Evaluation only'}</strong></span>`}
all('[data-template]').forEach(b=>b.onclick=()=>{if(busy)return toast('Wait for the current run.');chooseTemplate(b.dataset.template)});all('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#open-connections').onclick=()=>$('#connections-dialog').showModal();all('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#download').onclick=$('#install-side').onclick=()=>$('#download-dialog').showModal();$('#save').onclick=()=>{try{localStorage.setItem('bya-agents-v1',JSON.stringify(agents));toast('Agent settings saved in this browser.')}catch{toast('Browser storage is unavailable. Export your agent instead.')}};$('#export-agent').onclick=()=>{try{validateAgent(agent());exportFile('bya-'+current+'.agent.json',agent());toast('Agent exported. Import it in the local runtime.')}catch(e){toast(e.message)}};$('#export-ssot').onclick=()=>exportFile('bya-ssot.json',ssot);$('#arrange').onclick=()=>{agent().positions={};renderCanvas()};$('#canvas').ondragover=e=>e.preventDefault();$('#canvas').ondrop=e=>{e.preventDefault();addNode(e.dataTransfer.getData('text/plain'))};$('#run-top').onclick=$('#run-bottom').onclick=runTest;
$('#import-agent').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('Package exceeds 1 MB.');let a=JSON.parse(await f.text());validateAgent(a);agents[a.template]={...structuredClone(presets[a.template]),...a,positions:{}};chooseTemplate(a.template);$('#download-dialog').close();toast('Agent imported. Review settings before running.')}catch(err){toast(err.message)}finally{e.target.value=''}};
$('#import-ssot').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('SSOT exceeds 1 MB.');let doc=validateSSOT(JSON.parse(await f.text()));if(runtime)await api('/api/ssot',doc);else localStorage.setItem('bya-ssot-v1',JSON.stringify(doc));ssot=doc;renderSSOT();renderInspector();lastResult=null;$('#run-output').hidden=true;$('#run-empty').hidden=false;toast(runtime?'Local SSOT saved.':'SSOT imported in this browser. Export it for local execution.')}catch(err){toast(err.message)}finally{e.target.value=''}};
$('#copy-draft').onclick=async()=>{try{await navigator.clipboard.writeText(lastResult.draft);toast('Draft copied.')}catch{toast('Clipboard unavailable. Select the draft text to copy it.')}};
$('#approve').onclick=async()=>{if(!runtime||lastResult?.mode!=='live')return;const rid=lastResult.id;if(!confirm('Send this exact draft to your configured Slack channel?'))return;$('#approve').disabled=true;try{await api('/api/approve',{id:rid,confirm:'send'});lastResult.status='sent';$('#draft-state').textContent='Sent';$('#delivery-note').textContent='Delivered to the approved Slack channel.'}catch(e){toast(e.message);$('#delivery-note').textContent='Delivery not confirmed. Check Slack before retrying.'}};
let resize;window.addEventListener('resize',()=>{clearTimeout(resize);resize=setTimeout(()=>{renderCanvas();drawForecast()},150)});
async function init(){try{if(['localhost','127.0.0.1'].includes(location.hostname)){let r=await fetch('/api/status');if(r.ok)runtime=await r.json()}if(runtime){ssot=await (await fetch('/api/ssot')).json();$('#runtime-state').textContent='Local runtime';const downloadLink=$('a[href="bya-local-runtime.zip"]');downloadLink.removeAttribute('href');downloadLink.removeAttribute('download');downloadLink.textContent='Runtime already installed';$('#run-mode').options[1].disabled=false;$('#run-mode').options[1].text='Live connections';$('#storage-label').textContent='Local runtime · credentials stay on this computer';$('#prtg-status').textContent=runtime.prtg_configured?'Configured':'Not configured';$('#model-status').textContent=runtime.model?'Configured':'Not configured';$('#timesfm-status').textContent=runtime.timesfm_configured?'Path configured':'Not configured';$('#slack-status').textContent=runtime.slack_configured?'Configured':'Not configured'}else{try{ssot=JSON.parse(localStorage.getItem('bya-ssot-v1'))}catch{}if(!ssot)ssot=await(await fetch('sample-ssot.json')).json()}validateSSOT(ssot)}catch(e){toast('Could not load source of truth: '+e.message)}chooseTemplate('triage');registerTools()}
function registerTools(){if(!document.modelContext?.registerTool)return;const lifecycle=new AbortController();const defs=[{name:'bya_read_agent',description:'Read the current BYA agent configuration. No credentials are returned.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>structuredClone(agent())},{name:'bya_select_template',description:'Select an existing BYA template in the builder. Does not execute or send messages.',inputSchema:{type:'object',properties:{template:{type:'string',enum:['triage','forecast']}},required:['template'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(busy)throw Error('A run is active.');chooseTemplate(input.template);return {template:current,nodes:agent().nodes.length}}},{name:'bya_run_sample',description:'Run a synthetic sample of the current template. No model calls or external writes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{validateAgent(agent());lastResult=sampleRun();renderResult();return {status:lastResult.status,mode:'sample'}}}];for(const tool of defs)try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
init();
